# Generated by Django 5.2.1 on 2025-06-20 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('data_source_url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('publish_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('crawl_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('keywords', models.CharField(db_index=True, max_length=500)),
                ('type', models.CharField(choices=[('text', 'Text'), ('link', 'Link')], max_length=10)),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='crawls.webpage')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.AddField(
            model_name='webpage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpages', to='crawls.website'),
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('crawling', 'Crawling'), ('complete', 'Complete'), ('fail', 'Failed')], default='pending', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='crawls.website')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='images', serialize=False, to='crawls.datasource')),
                ('description', models.CharField(max_length=255)),
                ('resolution', models.CharField(max_length=50)),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crawls.webpage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='webpage',
            unique_together={('url', 'website')},
        ),
    ]
